version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: desafio-npl-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-npl-node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"