version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: desafio-npl-postgres
    environment:
      POSTGRES_DB: desafioNpl
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: npl
    ports:
      - "5432:5432"